'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sounds\bell1.mp3")>  _
        Public Property BellFile() As String
            Get
                Return CType(Me("BellFile"),String)
            End Get
            Set
                Me("BellFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sounds\gatha.mp3")>  _
        Public Property CMGFile() As String
            Get
                Return CType(Me("CMGFile"),String)
            End Get
            Set
                Me("CMGFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 08:20:00")>  _
        Public Property sp1() As Date
            Get
                Return CType(Me("sp1"),Date)
            End Get
            Set
                Me("sp1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 09:00:00")>  _
        Public Property sp2() As Date
            Get
                Return CType(Me("sp2"),Date)
            End Get
            Set
                Me("sp2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 09:40:00")>  _
        Public Property sp3() As Date
            Get
                Return CType(Me("sp3"),Date)
            End Get
            Set
                Me("sp3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 10:20:00")>  _
        Public Property sp4() As Date
            Get
                Return CType(Me("sp4"),Date)
            End Get
            Set
                Me("sp4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 10:40:00")>  _
        Public Property sbr() As Date
            Get
                Return CType(Me("sbr"),Date)
            End Get
            Set
                Me("sbr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 11:20:00")>  _
        Public Property sp5() As Date
            Get
                Return CType(Me("sp5"),Date)
            End Get
            Set
                Me("sp5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 12:00:00")>  _
        Public Property sp6() As Date
            Get
                Return CType(Me("sp6"),Date)
            End Get
            Set
                Me("sp6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 12:40:00")>  _
        Public Property sp7() As Date
            Get
                Return CType(Me("sp7"),Date)
            End Get
            Set
                Me("sp7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 13:20:00")>  _
        Public Property sp8() As Date
            Get
                Return CType(Me("sp8"),Date)
            End Get
            Set
                Me("sp8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 13:23:00")>  _
        Public Property sf1() As Date
            Get
                Return CType(Me("sf1"),Date)
            End Get
            Set
                Me("sf1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 13:25:00")>  _
        Public Property sf2() As Date
            Get
                Return CType(Me("sf2"),Date)
            End Get
            Set
                Me("sf2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("02/26/2016 13:30:00")>  _
        Public Property sf3() As Date
            Get
                Return CType(Me("sf3"),Date)
            End Get
            Set
                Me("sf3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RngMsgTM() As Boolean
            Get
                Return CType(Me("RngMsgTM"),Boolean)
            End Get
            Set
                Me("RngMsgTM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShwWar() As Boolean
            Get
                Return CType(Me("ShwWar"),Boolean)
            End Get
            Set
                Me("ShwWar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("buddhika")>  _
        Public Property SPassWord() As String
            Get
                Return CType(Me("SPassWord"),String)
            End Get
            Set
                Me("SPassWord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20, 20")>  _
        Public Property MainLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("MainLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("MainLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30, 30")>  _
        Public Property RngMsgLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("RngMsgLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("RngMsgLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property sDelay() As Integer
            Get
                Return CType(Me("sDelay"),Integer)
            End Get
            Set
                Me("sDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property sPrdDur() As Integer
            Get
                Return CType(Me("sPrdDur"),Integer)
            End Get
            Set
                Me("sPrdDur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property sBrBDur() As Integer
            Get
                Return CType(Me("sBrBDur"),Integer)
            End Get
            Set
                Me("sBrBDur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property sBrEDur() As Integer
            Get
                Return CType(Me("sBrEDur"),Integer)
            End Get
            Set
                Me("sBrEDur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property sF1Dur() As Integer
            Get
                Return CType(Me("sF1Dur"),Integer)
            End Get
            Set
                Me("sF1Dur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property sF2Dur() As Integer
            Get
                Return CType(Me("sF2Dur"),Integer)
            End Get
            Set
                Me("sF2Dur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property sF3Dur() As Integer
            Get
                Return CType(Me("sF3Dur"),Integer)
            End Get
            Set
                Me("sF3Dur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShtDwn() As Boolean
            Get
                Return CType(Me("ShtDwn"),Boolean)
            End Get
            Set
                Me("ShtDwn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property sVolume() As Integer
            Get
                Return CType(Me("sVolume"),Integer)
            End Get
            Set
                Me("sVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AskRW() As Boolean
            Get
                Return CType(Me("AskRW"),Boolean)
            End Get
            Set
                Me("AskRW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Protect() As Boolean
            Get
                Return CType(Me("Protect"),Boolean)
            End Get
            Set
                Me("Protect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property NBRDur() As Integer
            Get
                Return CType(Me("NBRDur"),Integer)
            End Get
            Set
                Me("NBRDur") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Period_Alarm_5._0.My.MySettings
            Get
                Return Global.Period_Alarm_5._0.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
